set(CMAKE_SYSTEM_NAME       FreeRTOS)
set(CMAKE_SYSTEM_PROCESSOR  arm)
set(MACHINE                 "metal" CACHE STRING "")


# Define TOOLCHAIN: COMPILER, ASSEMBLER, ACHIVER, LINKER
set (CROSS_PREFIX                   "arm-none-eabi-" CACHE STRING "")
find_program(CMAKE_C_COMPILER       NAMES "gcc")
find_program(CMAKE_CXX_COMPILER     NAMES "g++")
find_program(CMAKE_ASM_COMPILER     NAMES "gcc")
find_program(CMAKE_AR               NAMES "gcc-ar")
find_program(CMAKE_LINKER           NAMES "gcc")
find_program(CMAKE_OBJCOPY          NAMES "objcopy")
find_program(CMAKE_BIN_CONVERTER    NAMES "objcopy")

# Set build rule
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_USER_MAKE_RULES_OVERRIDE      ${CMAKE_CURRENT_LIST_FILE})
set(CMAKE_ASM_CREATE_STATIC_LIBRARY     "<CMAKE_AR> -r <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_CREATE_STATIC_LIBRARY       "<CMAKE_AR> -r <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY     "<CMAKE_AR> -r <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_C_ARCHIVE_CREATE              "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_LINK_EXECUTABLE             "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>")
set(CMAKE_CXX_LINK_EXECUTABLE           "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>")

include (cross-freertos-gcc)
