#ifndef _REG_X5H_MDLC_H_
#define _REG_X5H_MDLC_H_

/*************************************
 * Base Address
 *************************************/
#define MDLC_BASE_VIPN			(0xC3060000U)
#define MDLC_BASE_VIPS			(0xC3460000U)
#define MDLC_BASE_VIO 			(0xC5000000U)
#define MDLC_BASE_PERE			(0xC08F0000U)
#define MDLC_BASE_PERW			(0xC05D0000U)
#define MDLC_BASE_DDR0			(0xE8000000U)
#define MDLC_BASE_DDR1			(0xE8080000U)
#define MDLC_BASE_DDR2			(0xE8100000U)
#define MDLC_BASE_DDR3			(0xE8180000U)
#define MDLC_BASE_DDR4			(0xE8200000U)
#define MDLC_BASE_DDR5			(0xE8280000U)
#define MDLC_BASE_DDR6			(0xE8300000U)
#define MDLC_BASE_DDR7			(0xE8380000U)
#define MDLC_BASE_HSCN			(0xC9C90000U)
#define MDLC_BASE_RT  			(0x19440000U)
#define MDLC_BASE_TOP 			(0xC6480000U)
#define MDLC_BASE_HSCS			(0xDE200000U)
#define MDLC_BASE_IMN 			(0xC1990000U)
#define MDLC_BASE_IMS 			(0xC1D90000U)
#define MDLC_BASE_GPC 			(0xCB510000U)
#define MDLC_BASE_DSP 			(0xCBE90000U)
#define MDLC_BASE_MM  			(0xE9980000U)
#define MDLC_BASE_NPU0			(0xD2C30000U)
#define MDLC_BASE_NPU1			(0xD6C30000U)
#define MDLC_BASE_CMNN			(0xCA410000U)
#define MDLC_BASE_CMNS			(0xCA510000U)
#define MDLC_BASE_SCP 			(0xC1330000U)
#define MDLC_BASE_AON 			(0xC1338000U)


/*************************************
 * Register Offset (k=0~31, l=0~23)
 *************************************/
#define MDLC_SR_OFFSET				(0x0000U)
#define MDLC_ISCR_OFFSET			(0x0014U)
#define MDLC_MPISCR0_OFFSET			(0x0100U)
#define MDLC_MPIER0_OFFSET			(0x0110U)
#define MDLC_MPIMR0_OFFSET			(0x0120U)
#define MDLC_MPISOEHSR0_OFFSET		(0x0180U)
#define MDLC_MPISOELSR0_OFFSET		(0x0188U)
#define MDLC_MPISOEHIR0_OFFSET		(0x0190U)
#define MDLC_MPISOELIR0_OFFSET		(0x0198U)
#define MDLC_MPOFFSR0_OFFSET		(0x01B0U)
#define MDLC_MPONSR0_OFFSET			(0x01B8U)
#define MDLC_MPDG_OFFSET(k)			(0x0200U+(0x4*(k)))
#define MDLC_MPDGS_OFFSET(k)		(0x0300U+(0x4*(k)))
#define MDLC_MSRES_OFFSET(l)		(0x0900U+(0x4*(l)))
#define MDLC_MSRESS_OFFSET(l)		(0x0960U+(0x4*(l)))
#define MDLC_RAHSRMR_OFFSET(l)		(0x0A80U+(0x4*(l)))
#define MDLC_FSRCHKRA_OFFSET(l)		(0x0AE0U+(0x4*(l)))
#define MDLC_FSRCHKRB_OFFSET(l)		(0x0B40U+(0x4*(l)))
#define MDLC_FSRCHKSETR_OFFSET(l)	(0x0BA0U+(0x4*(l)))
#define MDLC_FSRCHKCLRR_OFFSET(l)	(0x0C00U+(0x4*(l)))
#define MDLC_RSSDER_OFFSET			(0x0CD0U)
#define MDLC_RSHLDCR_OFFSET			(0x0CD4U)
#define MDLC_RSSTPCR_OFFSET			(0x0CD8U)
#define MDLC_RTSRAMCR_OFFSET		(0x0050U)
#define MDLC_CR52RSTMSK_OFFSET		(0x0054U)
#define MDLC_PKCPROT0_OFFSET		(0x0CF0U)
#define MDLC_PKCPROT1_OFFSET		(0x0CF4U)

/*************************************
 * Register Access Macro
 *************************************/
/* MPDG */
#define MDLC_SR(base)				(base+MDLC_SR_OFFSET)
#define MDLC_ISCR(base)				(base+MDLC_ISCR_OFFSET)
#define MDLC_MPISCR0(base)			(base+MDLC_MPISCR0_OFFSET)
#define MDLC_MPIER0(base)			(base+MDLC_MPIER0_OFFSET)
#define MDLC_MPIMR0(base)			(base+MDLC_MPIMR0_OFFSET)
#define MDLC_MPISOEHSR0(base)		(base+MDLC_MPISOEHSR0_OFFSET)
#define MDLC_MPISOELSR0(base)		(base+MDLC_MPISOELSR0_OFFSET)
#define MDLC_MPISOEHIR0(base)		(base+MDLC_MPISOEHIR0_OFFSET)
#define MDLC_MPISOELIR0(base)		(base+MDLC_MPISOELIR0_OFFSET)
#define MDLC_MPOFFSR0(base)			(base+MDLC_MPOFFSR0_OFFSET)
#define MDLC_MPONSR0(base)			(base+MDLC_MPONSR0_OFFSET)
#define MDLC_MPDG(base,pdid)		(base+MDLC_MPDG_OFFSET(pdid))
#define MDLC_MPDGS(base,pdid)		(base+MDLC_MPDGS_OFFSET(pdid))
#define MDLC_MSRES(base,regNo)		(base+MDLC_MSRES_OFFSET(regNo))
#define MDLC_MSRESS(base,regNo)		(base+MDLC_MSRESS_OFFSET(regNo))
#define MDLC_RAHSRMR(base,l)		(base+MDLC_RAHSRMR_OFFSET(l))
#define MDLC_FSRCHKRA(base,l)		(base+MDLC_FSRCHKRA_OFFSET(l))
#define MDLC_FSRCHKRB(base,l)		(base+MDLC_FSRCHKRB_OFFSET(l))
#define MDLC_FSRCHKSETR(base,l)		(base+MDLC_FSRCHKSETR_OFFSET(l))
#define MDLC_FSRCHKCLRR(base,l)		(base+MDLC_FSRCHKCLRR_OFFSET(l))
#define MDLC_RSSDER(base)			(base+MDLC_RSSDER_OFFSET)
#define MDLC_RSHLDCR(base)			(base+MDLC_RSHLDCR_OFFSET)
#define MDLC_RSSTPCR(base)			(base+MDLC_RSSTPCR_OFFSET)
#define MDLC_RTSRAMCR(base)			(base+MDLC_RTSRAMCR_OFFSET)
#define MDLC_CR52RSTMSK(base)		(base+MDLC_CR52RSTMSK_OFFSET)
#define MDLC_PKCPROT0(base)			(base+MDLC_PKCPROT0_OFFSET)
#define MDLC_PKCPROT1(base)			(base+MDLC_PKCPROT1_OFFSET)

#endif /* _REG_X5H_MDLC_H_ */

