#ifndef _REG_X5H_DMAC_H_
#define _REG_X5H_DMAC_H_

/*******************************************************************************
  Base Address
*******************************************************************************/
#define RT_DMACP0_BASE     (0x19438000U)
#define RT_DMACP1_BASE     (0x19439000U)
#define RT_DMACP2_BASE     (0x1943A000U)
#define RT_DMACP3_BASE     (0x1943B000U)

#define SYS_DMACP00_BASE   (0xC0940000U)
#define SYS_DMACP10_BASE   (0xC05C4000U)
#define SYS_DMACP11_BASE   (0xC05C5000U)
#define SYS_DMACP12_BASE   (0xC05C6000U)

#define SCP_DMACP0_BASE    (0xC11E8000U)
#define SCP_DMACP1_BASE    (0xC11E9000U)

/* m = 0~3 */
#define RT_DMACPm_BASE(m)  (RT_DMACP0_BASE + ((m) * 0x1000U))

/* n = 0~15 */
#define RT_DMAC0CHn_BASE(n)     (0x18900000U + ((n) * 0x1000U))
#define RT_DMAC1CHn_BASE(n)     (0x18910000U + ((n) * 0x1000U))
#define RT_DMAC2CHn_BASE(n)     (0x18920000U + ((n) * 0x1000U))
#define RT_DMAC3CHn_BASE(n)     (0x18930000U + ((n) * 0x1000U))
#define RT_DMACmCHn_BASE(m,n)   (0x18900000U + ((n) * 0x1000U) + ((m) * 0x10000U))

#define SYS_DMAC00CHn_BASE(n)   (0xC0900000U + ((n) * 0x1000U))
#define SYS_DMAC10CHn_BASE(n)   (0xC0480000U + ((n) * 0x1000U))
#define SYS_DMAC11CHn_BASE(n)   (0xC0490000U + ((n) * 0x1000U))
#define SYS_DMAC12CHn_BASE(n)   (0xC04A0000U + ((n) * 0x1000U))
#define SCP_DMAC0CHn_BASE(n)    (0xC11A0000U + ((n) * 0x1000U))
#define SCP_DMAC1CHn_BASE(n)    (0xC11B0000U + ((n) * 0x1000U))

/*******************************************************************************
  Register Offset
*******************************************************************************/
/* RT-DMACP */
#define RDMOR_OFFSET                   (0x0060U)
#define RDMBUFMODE_OFFSET              (0x00A4U)
#define RDMERRDET_OFFSET               (0x00C0U)
#define RDMERRADR_OFFSET               (0x00C4U)
#define RDMERRPID_OFFSET               (0x00C8U)
#define RDMAPBEDC_OFFSET               (0x00D0U)
#define RDMAPB_CH_PADDR_OFFSET         (0x00D4U)
#define RDMAPB_CH_PWDATA_OFFSET        (0x00D8U)
#define RDMAPB_PUBLIC_PADDR_OFFSET     (0x00DCU)
#define RDMAPB_PUBLIC_PWDATA_OFFSET    (0x00E0U)
#define RDMCMP_STATUS_OFFSET           (0x00F0U)
#define RDMRATE_RD_OFFSET              (0x00F4U)
#define RDMRATE_WR_OFFSET              (0x00F8U)

/* RT-DMAC in Channel */
#define RDMSAR_OFFSET          (0x0000U)
#define RDMDAR_OFFSET          (0x0004U)
#define RDMTCR_OFFSET          (0x0008U)
#define RDMFIXSAR_OFFSET       (0x0010U)
#define RDMCHCR_OFFSET         (0x000CU)
#define RDMFIXSAR_OFFSET       (0x0010U)
#define RDMFIXDAR_OFFSET       (0x0014U)
#define RDMTCRB_OFFSET         (0x0018U)
#define RDMCHCRB_OFFSET        (0x001CU)
#define RDMSARS_OFFSET         (0x0020U)
#define RDMDARS_OFFSET         (0x0024U)
#define RDMTSR_OFFSET          (0x0028U)
#define RDMCHCRS_OFFSET        (0x002CU)
#define RDMTSRB_OFFSET         (0x0038U)
#define RDMDMRS_OFFSET         (0x0040U)
#define RDMBUFCR_OFFSET        (0x0048U)
#define RDMDPBASE_OFFSET       (0x0050U)
#define RDMDPCR_OFFSET         (0x0054U)
#define RDMDPEVTCR_OFFSET      (0x0058U)
#define RDMDPEVTCNT_OFFSET     (0x005CU)
#define RDMFIXDPBASE_OFFSET    (0x0060U)
#define RDMDREQOS_OFFSET       (0x0064U)
#define RDMREGIONID_OFFSET     (0x0078U)
#define RDMCHID_OFFSET         (0x0080U)
#define RDMDMSEC_OFFSET        (0x00B0U)
#define RDMCHCLR_OFFSET        (0x0100U)
#define RDMISTA_OFFSET         (0x0110U)
#define RDMADR40MODE_OFFSET    (0x0114U)

/* SYS-DMAC */
#define SDMOR_OFFSET                   (0x0060U)
#define SDMBUFMODE_OFFSET              (0x00A4U)
#define SDMERRDET_OFFSET               (0x00C0U)
#define SDMERRADR_OFFSET               (0x00C4U)
#define SDMERRPID_OFFSET               (0x00C8U)
#define SDMAPBEDC_OFFSET               (0x00D0U)
#define SDMAPB_CH_PADDR_OFFSET         (0x00D4U)
#define SDMAPB_CH_PWDATA_OFFSET        (0x00D8U)
#define SDMAPB_PUBLIC_PADDR_OFFSET     (0x00DCU)
#define SDMAPB_PUBLIC_PWDATA_OFFSET    (0x00E0U)
#define SDMCMP_STATUS_OFFSET           (0x00F0U)
#define SDMRATE_RD_OFFSET              (0x00F4U)
#define SDMRATE_WR_OFFSET              (0x00F8U)

/* SYS-DMAC in Channel */
#define SDMSAR_OFFSET          (0x0000U)
#define SDMDAR_OFFSET          (0x0004U)
#define SDMTCR_OFFSET          (0x0008U)
#define SDMCHCR_OFFSET         (0x000CU)
#define SDMFIXSAR_OFFSET       (0x0010U)
#define SDMFIXDAR_OFFSET       (0x0014U)
#define SDMTCRB_OFFSET         (0x0018U)
#define SDMCHCRB_OFFSET        (0x001CU)
#define SDMSARS_OFFSET         (0x0020U)
#define SDMDARS_OFFSET         (0x0024U)
#define SDMTSR_OFFSET          (0x0028U)
#define SDMCHCRS_OFFSET        (0x002CU)
#define SDMTSRB_OFFSET         (0x0038U)
#define SDMDMRS_OFFSET         (0x0040U)
#define SDMBUFCR_OFFSET        (0x0048U)
#define SDMDPBASE_OFFSET       (0x0050U)
#define SDMDPCR_OFFSET         (0x0054U)
#define SDMDPEVTCR_OFFSET      (0x0058U)
#define SDMDPEVTCNT_OFFSET     (0x005CU)
#define SDMFIXDPBASE_OFFSET    (0x0060U)
#define SDMDREQOS_OFFSET       (0x0064U)
#define SDMREGIONID_OFFSET     (0x0078U)
#define SDMCHID_OFFSET         (0x0080U)
#define SDMDMSEC_OFFSET        (0x00B0U)
#define SDMCHCLR_OFFSET        (0x0100U)
#define SDMISTA_OFFSET         (0x0110U)

/* SCP-DMAC */
#define OR_OFFSET                   (0x0060U)
#define BUFMODE_OFFSET              (0x00A4U)
#define ERRDET_OFFSET               (0x00C0U)
#define ERRADR_OFFSET               (0x00C4U)
#define ERRPID_OFFSET               (0x00C8U)
#define APBEDC_OFFSET               (0x00D0U)
#define APB_CH_PADDR_OFFSET         (0x00D4U)
#define APB_CH_PWDATA_OFFSET        (0x00D8U)
#define APB_PUBLIC_PADDR_OFFSET     (0x00DCU)
#define APB_PUBLIC_PWDATA_OFFSET    (0x00E0U)
#define CMP_STATUS_OFFSET           (0x00F0U)
#define RATE_RD_OFFSET              (0x00F4U)
#define RATE_WR_OFFSET              (0x00F8U)

/* SCP-DMAC in Channel */
#define SAR_OFFSET                  (0x0000U)
#define DAR_OFFSET                  (0x0004U)
#define TCR_OFFSET                  (0x0008U)
#define CHCR_OFFSET                 (0x000CU)
#define FIXSAR_OFFSET               (0x0010U)
#define FIXDAR_OFFSET               (0x0014U)
#define TCRB_OFFSET                 (0x0018U)
#define CHCRB_OFFSET                (0x001CU)
#define SARS_OFFSET                 (0x0020U)
#define DARS_OFFSET                 (0x0024U)
#define TSR_OFFSET                  (0x0028U)
#define CHCRS_OFFSET                (0x002CU)
#define TSRB_OFFSET                 (0x0038U)
#define DMRS_OFFSET                 (0x0040U)
#define BUFCR_OFFSET                (0x0048U)
#define DPBASE_OFFSET               (0x0050U)
#define DPCR_OFFSET                 (0x0054U)
#define DPEVTCR_OFFSET              (0x0058U)
#define DPEVTCNT_OFFSET             (0x005CU)
#define FIXDPBASE_OFFSET            (0x0060U)
#define DREQOS_OFFSET               (0x0064U)
#define REGIONID_OFFSET             (0x0078U)
#define CHID_OFFSET                 (0x0080U)
#define DMSEC_OFFSET                (0x00B0U)
#define CHCLR_OFFSET                (0x0100U)
#define ISTA_OFFSET                 (0x0110U)

/*******************************************************************************
  Register Access Macro
*******************************************************************************/
/* RT-DMAC0 */
#define DMAC_RDMOR					(uintptr_t)(RT_DMACP0_BASE       + RDMOR_OFFSET)
#define DMAC_RDM0_SAR(ch)			(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMSAR_OFFSET)
#define DMAC_RDM0_DAR(ch)			(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMDAR_OFFSET)
#define DMAC_RDM0_TCR(ch)			(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMTCR_OFFSET)
#define DMAC_RDM0_CHCR(ch)			(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMCHCR_OFFSET)
#define DMAC_RDM0_CHCLR(ch)			(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMCHCLR_OFFSET)
#define DMAC_RDM0_FIXSAR(ch)		(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMFIXSAR_OFFSET)
#define DMAC_RDM0_FIXDAR(ch)		(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMFIXDAR_OFFSET)
#define DMAC_RDM0_RDMBUFCR(ch)		(uintptr_t)(RT_DMAC0CHn_BASE(ch) + RDMBUFCR_OFFSET)

/* RT-DMACm */
#define DMAC_RDMORm(m)				(uintptr_t)(RT_DMACPm_BASE(m)      + RDMOR_OFFSET)
#define DMAC_RDM_SAR(m,ch)			(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMSAR_OFFSET)
#define DMAC_RDM_DAR(m,ch)			(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMDAR_OFFSET)
#define DMAC_RDM_TCR(m,ch)			(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMTCR_OFFSET)
#define DMAC_RDM_CHCR(m,ch)			(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMCHCR_OFFSET)
#define DMAC_RDM_CHCLR(m,ch)		(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMCHCLR_OFFSET)
#define DMAC_RDM_FIXSAR(m,ch)		(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMFIXSAR_OFFSET)
#define DMAC_RDM_FIXDAR(m,ch)		(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMFIXDAR_OFFSET)
#define DMAC_RDM_RDMBUFCR(m,ch)		(uintptr_t)(RT_DMACmCHn_BASE(m,ch) + RDMBUFCR_OFFSET)

/* SYS-DMAC */
#define DMAC_SDMOR					(uintptr_t)(SYS_DMACP00_BASE       + SDMOR_OFFSET)
#define DMAC_SDM0_SAR(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMSAR_OFFSET)
#define DMAC_SDM0_DAR(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMDAR_OFFSET)
#define DMAC_SDM0_TCR(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMTCR_OFFSET)
#define DMAC_SDM0_CHCR(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMCHCR_OFFSET)
#define DMAC_SDM0_CHCLR(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMCHCLR_OFFSET)
#define DMAC_SDM0_DMSEC(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMDMSEC_OFFSET)
#define DMAC_SDM0_DMRS(ch)			(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMDMRS_OFFSET)
#define DMAC_SDM0_FIXSAR(ch)		(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMFIXSAR_OFFSET)
#define DMAC_SDM0_FIXDAR(ch)		(uintptr_t)(SYS_DMAC00CHn_BASE(ch) + SDMFIXDAR_OFFSET)

/* SCP-DMAC */
#define SCPDMAC0_OR					(uintptr_t)(SCP_DMACP0_BASE       + OR_OFFSET)
#define SCPDMAC0_SAR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + SAR_OFFSET)
#define SCPDMAC0_DAR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + DAR_OFFSET)
#define SCPDMAC0_TCR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + TCR_OFFSET)
#define SCPDMAC0_TCRB(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + TCRB_OFFSET)
#define SCPDMAC0_CHCR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + CHCR_OFFSET)
#define SCPDMAC0_CHCLR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + CHCLR_OFFSET)
#define SCPDMAC0_DMSEC(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + DMSEC_OFFSET)
#define SCPDMAC0_DMRS(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + DMRS_OFFSET)
#define SCPDMAC0_FIXSAR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + FIXSAR_OFFSET)
#define SCPDMAC0_FIXDAR(ch)			(uintptr_t)(SCP_DMAC0CHn_BASE(ch) + FIXDAR_OFFSET)

#endif /* _REG_X5H_DMAC_H_ */
